[package]
name = "typenum-fractional"
version = "0.1.0"
edition = "2018"

categories = ["no-std"]

[dependencies]
typenum = { version = "^1.1.12", default-features = false }
const-default = { version = "^0.1.0", git = "https://github.com/AerialX/const-default.rs" }

[features]
unstable = [ ]
